version: 2.1

executors:
  app-executor:
    docker:
      - image: circleci/node:12.9.1-browsers

jobs:
  build-app:
    executor: app-executor
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Test Cases
          command: npm test
      - build:
          name: Build App
          command: npm run build

workflows:
  build-workflow:
    jobs:
      - build-app
